-- MySQL Workbench Synchronization
-- Generated: 2018-07-28 17:46
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Roncarlos

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE TABLE IF NOT EXISTS `discord_bot_rpg`.`serversstats` (
  `idServer` VARCHAR(21) NOT NULL,
  `serverPrefix` VARCHAR(10) NULL DEFAULT NULL,
  `serverName` VARCHAR(101) NOT NULL DEFAULT 'unknown',
  `memberCount` INT(11) NOT NULL DEFAULT 0,
  `region` TEXT NOT NULL,
  PRIMARY KEY (`idServer`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
