-- MySQL Workbench Synchronization
-- Generated: 2018-10-30 11:40
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Roncarlos

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS
, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS
, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE
, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `discord_bot_rpg`.`areasitems`
ADD COLUMN `percentage` FLOAT
(10) UNSIGNED NOT NULL DEFAULT 0 AFTER `idBaseItem`,
ADD COLUMN `min` INT
(10) UNSIGNED NOT NULL DEFAULT 1 AFTER `percentage`,
ADD COLUMN `max` INT
(10) UNSIGNED NOT NULL DEFAULT 1 AFTER `min`;


SET SQL_MODE
=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS
=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS
=@OLD_UNIQUE_CHECKS;
