-- MySQL Script generated by MySQL Workbench
-- Mon Jan 15 17:13:31 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema discord_bot_rpg
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `discord_bot_rpg` ;

-- -----------------------------------------------------
-- Schema discord_bot_rpg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `discord_bot_rpg` DEFAULT CHARACTER SET utf8 ;
USE `discord_bot_rpg` ;

-- -----------------------------------------------------
-- Table `discord_bot_rpg`.`Stats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discord_bot_rpg`.`Stats` ;

CREATE TABLE IF NOT EXISTS `discord_bot_rpg`.`Stats` (
  `idStat` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `frc` INT UNSIGNED NOT NULL,
  `intelligence` INT UNSIGNED NOT NULL,
  `constitution` INT UNSIGNED NOT NULL,
  `defense` INT UNSIGNED NOT NULL,
  `dexterite` INT UNSIGNED NOT NULL,
  `sagesse` INT UNSIGNED NOT NULL,
  `volonte` INT UNSIGNED NOT NULL,
  `perception` INT UNSIGNED NOT NULL,
  `charisme` INT UNSIGNED NOT NULL,
  `luck` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idStat`),
  UNIQUE INDEX `idStats_UNIQUE` (`idStat` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `discord_bot_rpg`.`LevelsRequire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discord_bot_rpg`.`LevelsRequire` ;

CREATE TABLE IF NOT EXISTS `discord_bot_rpg`.`LevelsRequire` (
  `level` INT UNSIGNED NOT NULL,
  `expNextLevel` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`level`),
  UNIQUE INDEX `level_UNIQUE` (`level` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `discord_bot_rpg`.`Levels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discord_bot_rpg`.`Levels` ;

CREATE TABLE IF NOT EXISTS `discord_bot_rpg`.`Levels` (
  `idLevel` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `actualExp` INT UNSIGNED NOT NULL,
  `actualLevel` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idLevel`),
  UNIQUE INDEX `idLevel_UNIQUE` (`idLevel` ASC),
  INDEX `fk_Levels_LevelsRequire1_idx` (`actualLevel` ASC),
  CONSTRAINT `fk_Levels_LevelsRequire1`
    FOREIGN KEY (`actualLevel`)
    REFERENCES `discord_bot_rpg`.`LevelsRequire` (`level`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `discord_bot_rpg`.`Characters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discord_bot_rpg`.`Characters` ;

CREATE TABLE IF NOT EXISTS `discord_bot_rpg`.`Characters` (
  `idCharacter` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idStat` INT UNSIGNED NOT NULL,
  `idLevel` INT UNSIGNED NOT NULL,
  `statPoints` INT UNSIGNED NOT NULL,
  `money` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCharacter`),
  UNIQUE INDEX `idCharacter_UNIQUE` (`idCharacter` ASC),
  INDEX `fk_Character_Stats1_idx` (`idStat` ASC),
  UNIQUE INDEX `idStat_UNIQUE` (`idStat` ASC),
  INDEX `fk_Characters_Levels1_idx` (`idLevel` ASC),
  CONSTRAINT `fk_Character_Stats1`
    FOREIGN KEY (`idStat`)
    REFERENCES `discord_bot_rpg`.`Stats` (`idStat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Characters_Levels1`
    FOREIGN KEY (`idLevel`)
    REFERENCES `discord_bot_rpg`.`Levels` (`idLevel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `discord_bot_rpg`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discord_bot_rpg`.`Users` ;

CREATE TABLE IF NOT EXISTS `discord_bot_rpg`.`Users` (
  `idUser` VARCHAR(20) NOT NULL,
  `idCharacter` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUsers_UNIQUE` (`idUser` ASC),
  INDEX `fk_Users_Character_idx` (`idCharacter` ASC),
  UNIQUE INDEX `idCharacter_UNIQUE` (`idCharacter` ASC),
  CONSTRAINT `fk_Users_Character`
    FOREIGN KEY (`idCharacter`)
    REFERENCES `discord_bot_rpg`.`Characters` (`idCharacter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `discord_bot_rpg`.`StatsMonstres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discord_bot_rpg`.`StatsMonstres` ;

CREATE TABLE IF NOT EXISTS `discord_bot_rpg`.`StatsMonstres` (
  `idStat` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `frc` INT UNSIGNED NOT NULL,
  `intelligence` INT UNSIGNED NOT NULL,
  `constitution` INT UNSIGNED NOT NULL,
  `defense` INT UNSIGNED NOT NULL,
  `dexterite` INT UNSIGNED NOT NULL,
  `sagesse` INT UNSIGNED NOT NULL,
  `volonte` INT UNSIGNED NOT NULL,
  `perception` INT UNSIGNED NOT NULL,
  `charisme` INT UNSIGNED NOT NULL,
  `luck` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idStat`),
  UNIQUE INDEX `idStats_UNIQUE` (`idStat` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `discord_bot_rpg`.`MonstresTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discord_bot_rpg`.`MonstresTypes` ;

CREATE TABLE IF NOT EXISTS `discord_bot_rpg`.`MonstresTypes` (
  `idType` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idType`),
  UNIQUE INDEX `idType_UNIQUE` (`idType` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `discord_bot_rpg`.`Monstres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discord_bot_rpg`.`Monstres` ;

CREATE TABLE IF NOT EXISTS `discord_bot_rpg`.`Monstres` (
  `idMonstre` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `avglevel` INT UNSIGNED NOT NULL,
  `idStat` INT UNSIGNED NOT NULL,
  `idType` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idMonstre`),
  UNIQUE INDEX `idMonstre_UNIQUE` (`idMonstre` ASC),
  INDEX `fk_Monstres_StatsMonstres1_idx` (`idStat` ASC),
  UNIQUE INDEX `idStat_UNIQUE` (`idStat` ASC),
  INDEX `fk_Monstres_MonstresTypes1_idx` (`idType` ASC),
  CONSTRAINT `fk_Monstres_StatsMonstres1`
    FOREIGN KEY (`idStat`)
    REFERENCES `discord_bot_rpg`.`StatsMonstres` (`idStat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Monstres_MonstresTypes1`
    FOREIGN KEY (`idType`)
    REFERENCES `discord_bot_rpg`.`MonstresTypes` (`idType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `discord_bot_rpg`.`LevelsRequire`
-- -----------------------------------------------------
START TRANSACTION;
USE `discord_bot_rpg`;
INSERT INTO `discord_bot_rpg`.`LevelsRequire` (`level`, `expNextLevel`) VALUES (1, 100);

COMMIT;


-- -----------------------------------------------------
-- Data for table `discord_bot_rpg`.`StatsMonstres`
-- -----------------------------------------------------
START TRANSACTION;
USE `discord_bot_rpg`;
INSERT INTO `discord_bot_rpg`.`StatsMonstres` (`idStat`, `frc`, `intelligence`, `constitution`, `defense`, `dexterite`, `sagesse`, `volonte`, `perception`, `charisme`, `luck`) VALUES (1, 5, 0, 5, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO `discord_bot_rpg`.`StatsMonstres` (`idStat`, `frc`, `intelligence`, `constitution`, `defense`, `dexterite`, `sagesse`, `volonte`, `perception`, `charisme`, `luck`) VALUES (2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `discord_bot_rpg`.`MonstresTypes`
-- -----------------------------------------------------
START TRANSACTION;
USE `discord_bot_rpg`;
INSERT INTO `discord_bot_rpg`.`MonstresTypes` (`idType`, `nom`) VALUES (1, 'Normal');

COMMIT;


-- -----------------------------------------------------
-- Data for table `discord_bot_rpg`.`Monstres`
-- -----------------------------------------------------
START TRANSACTION;
USE `discord_bot_rpg`;
INSERT INTO `discord_bot_rpg`.`Monstres` (`idMonstre`, `name`, `avglevel`, `idStat`, `idType`) VALUES (1, 'Ganguizz', 2, 1, 1);
INSERT INTO `discord_bot_rpg`.`Monstres` (`idMonstre`, `name`, `avglevel`, `idStat`, `idType`) VALUES (2, 'Slime', 1, 2, 1);

COMMIT;

